spring:
  application:
    name: codingtest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /train-management
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    title: "Alstom Coding Test"
    description: "Alstom Coding Test"
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-query-params: true
    display-operation-id: true
    display-request-duration: true
    doc-expansion: none